version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $root_pass
      MYSQL_DATABASE: $db_name
      MYSQL_USER: $root_name
      MYSQL_PASSWORD: $root_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    deploy:
      replicas: $n_cont
      placement:
        constraints:
          - node.role == worker
